### ISSUE TITLE
是否考慮新增 每周梗圖

### ISSUE THREAD

**Issue by onon1101** [ntut-open-source-club/PTSD-Practice-Giraffe-Adventure#3]
### 例子：
![image](https://github.com/ntut-open-source-club/PTSD-Practice-Giraffe-Adventure/assets/98307453/694bdbfb-5ccf-4fde-b303-151ded0b5a6a)

### Reference
link: https://hackmd.io/@OOP2023f/S1I0sLHkT

**Comment by PEKKA1117** [comment]
![image](https://github.com/ntut-open-source-club/PTSD-Practice-Giraffe-Adventure/assets/55215882/5e69258d-af74-4efc-b9ce-5ee0e56dceb9)
Week 1
![](https://cdn.discordapp.com/attachments/1093938857772322886/1210943171836776468/image.png?ex=65ec65b6&is=65d9f0b6&hm=66b7694a39924cd5acb2267f409f59c0937b4728a75eed72228c1413140d1154&)
